name: Releases

on:
  push:
    tags: '3*'

jobs:
  build-binaries:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl]
        os: [ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Generate version file
      shell: bash
      run: echo $(git -C $GITHUB_WORKSPACE describe --tags --abbrev=0) > version

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y flatpak-builder

    - name: Build Flatpak
      shell: bash
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

        sudo flatpak install --noninteractive org.gnome.Platform/x86_64/46
        sudo flatpak install --noninteractive org.gnome.Sdk/x86_64/46
        make flatpak-repository
        make flatpak-bundle
        mv nyxt.flatpak nyxt-$(cat version)-webkitgtk.flatpak

    - name: Generate release notes
      shell: bash
      run: |
        echo "Release notes: https://nyxt-browser.com/article/release-$(cat version).org" >> release.txt
        echo "" >> release.txt
        echo "To compile from source, prefer the tarball including the submodules if you don't manage the Lisp dependencies yourself." >> release.txt

    - name: Generate source archive with submodules
      shell: bash
      run: git ls-files --recurse-submodules | tar caf nyxt-$(cat version)-source-with-submodules.tar.xz -T-

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: release.txt
        artifacts: "nyxt-*.tar.xz*,*.flatpak"
